import {
  CONTROL_PROTOCOL_VERSION, MAC_HEX_RE, NONCE_HEX_RE, UUID_V4_RE,
  isControlMessageType, type AnyControlMessage, type ControlHandshakeFrame, type ControlMessageType, type Hello1Frame, type Hello2Frame, type SealedControlFrame,
} from './ControlMessage';
import { isSafePrivateHostCandidate, isSafeVideoSdp } from './MediaValidation';

const MAX_CONTROL_FRAME_BYTES = 48 * 1024;
const MAX_SEALED_WIRE_CHARS = 40 * 1024;
const encoder = new TextEncoder();
export class ControlCodecError extends Error { constructor(message: string) { super(message); this.name = 'ControlCodecError'; } }
function exactKeys(value: Record<string, unknown>, expected: readonly string[]): boolean { const keys = Object.keys(value).sort(); const wanted = [...expected].sort(); return keys.length === wanted.length && keys.every((key, index) => key === wanted[index]); }
function objectValue(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new ControlCodecError(`${label} must be an object.`); return value as Record<string, unknown>; }
function parseJson(frame: string): Record<string, unknown> { if (typeof frame !== 'string' || !frame || encoder.encode(frame).byteLength > MAX_CONTROL_FRAME_BYTES) throw new ControlCodecError('Control frame size is invalid.'); let parsed: unknown; try { parsed = JSON.parse(frame); } catch { throw new ControlCodecError('Control frame is not valid JSON.'); } return objectValue(parsed, 'Control frame'); }
function requireUuid(value: unknown, label: string): string { if (typeof value !== 'string' || !UUID_V4_RE.test(value)) throw new ControlCodecError(`${label} is invalid.`); return value.toLowerCase(); }
function requireTimestamp(value: unknown): string { if (typeof value !== 'string') throw new ControlCodecError('Control timestamp is invalid.'); const parsed = Date.parse(value); if (Number.isNaN(parsed) || new Date(parsed).toISOString() !== value) throw new ControlCodecError('Control timestamp must be canonical UTC ISO-8601.'); return value; }
function requireSequence(value: unknown): number { if (!Number.isSafeInteger(value) || (value as number) < 1 || (value as number) > 0x7fffffff) throw new ControlCodecError('Control sequence is invalid.'); return value as number; }
function requireNonce(value: unknown): string { if (typeof value !== 'string' || !NONCE_HEX_RE.test(value)) throw new ControlCodecError('Control nonce is invalid.'); return value.toLowerCase(); }
function requireMac(value: unknown): string { if (typeof value !== 'string' || !MAC_HEX_RE.test(value)) throw new ControlCodecError('Control authentication tag is invalid.'); return value.toLowerCase(); }
function requireVersion(value: unknown): typeof CONTROL_PROTOCOL_VERSION { if (value !== CONTROL_PROTOCOL_VERSION) throw new ControlCodecError('Unsupported control protocol version.'); return CONTROL_PROTOCOL_VERSION; }
function parsePayload(type: ControlMessageType, value: unknown): AnyControlMessage['payload'] {
  const payload = objectValue(value, 'Control payload');
  if (type === 'REQUEST_SCREEN') { if (!exactKeys(payload, ['expiresAt']) || typeof payload.expiresAt !== 'string') throw new ControlCodecError('REQUEST_SCREEN payload is invalid.'); requireTimestamp(payload.expiresAt); return { expiresAt: payload.expiresAt }; }
  if (type === 'REQUEST_CANCEL') { if (!exactKeys(payload, ['reason']) || (payload.reason !== 'user' && payload.reason !== 'timeout')) throw new ControlCodecError('REQUEST_CANCEL payload is invalid.'); return { reason: payload.reason }; }
  if (type === 'ACCEPT_SCREEN') { if (!exactKeys(payload, [])) throw new ControlCodecError('ACCEPT_SCREEN payload is invalid.'); return {}; }
  if (type === 'DECLINE_SCREEN') { if (!exactKeys(payload, ['reason']) || (payload.reason !== 'declined' && payload.reason !== 'busy')) throw new ControlCodecError('DECLINE_SCREEN payload is invalid.'); return { reason: payload.reason }; }
  if (type === 'CAPTURE_DENIED') { if (!exactKeys(payload, ['reason']) || (payload.reason !== 'system_denied' && payload.reason !== 'notifications_denied')) throw new ControlCodecError('CAPTURE_DENIED payload is invalid.'); return { reason: payload.reason }; }
  if (type === 'SDP_OFFER' || type === 'SDP_ANSWER') { if (!exactKeys(payload, ['sdp']) || !isSafeVideoSdp(payload.sdp)) throw new ControlCodecError(`${type} payload is invalid.`); return { sdp: payload.sdp }; }
  if (type === 'ICE_CANDIDATE') { if (!exactKeys(payload, ['sdpMid', 'sdpMLineIndex', 'candidate']) || typeof payload.sdpMid !== 'string' || payload.sdpMid.length > 64 || !Number.isInteger(payload.sdpMLineIndex) || (payload.sdpMLineIndex as number) < 0 || (payload.sdpMLineIndex as number) > 32 || !isSafePrivateHostCandidate(payload.candidate)) throw new ControlCodecError('ICE_CANDIDATE payload is invalid.'); return { sdpMid: payload.sdpMid, sdpMLineIndex: payload.sdpMLineIndex as number, candidate: payload.candidate }; }
  if (type === 'MEDIA_RESTART_REQUEST') { if (!exactKeys(payload, ['reason']) || payload.reason !== 'connection_lost') throw new ControlCodecError('MEDIA_RESTART_REQUEST payload is invalid.'); return { reason: 'connection_lost' }; }
  if (type === 'MEDIA_KEYFRAME_REQUEST') { if (!exactKeys(payload, ['reason']) || payload.reason !== 'first_frame') throw new ControlCodecError('MEDIA_KEYFRAME_REQUEST payload is invalid.'); return { reason: 'first_frame' }; }
  if (type === 'SESSION_END') { if (!exactKeys(payload, ['reason']) || !['user', 'disconnect', 'timeout'].includes(String(payload.reason))) throw new ControlCodecError('SESSION_END payload is invalid.'); return { reason: payload.reason as 'user' | 'disconnect' | 'timeout' }; }
  if (!exactKeys(payload, ['reason']) || !['busy', 'invalid_transition', 'timeout', 'auth_failed', 'capture_failed', 'capture_revoked', 'media_failed'].includes(String(payload.reason))) throw new ControlCodecError('SESSION_ERROR payload is invalid.');
  return { reason: payload.reason as 'busy' | 'invalid_transition' | 'timeout' | 'auth_failed' | 'capture_failed' | 'capture_revoked' | 'media_failed' };
}
export function encodeControlMessage(message: AnyControlMessage): string { return JSON.stringify(message); }
export function decodeControlMessage(frame: string): AnyControlMessage { const value = parseJson(frame); if (!exactKeys(value, ['version', 'messageId', 'type', 'sessionId', 'senderDeviceId', 'sequence', 'timestamp', 'payload'])) throw new ControlCodecError('Control message has unsupported fields.'); const type = value.type; if (!isControlMessageType(type)) throw new ControlCodecError('Control message type is invalid.'); return { version: requireVersion(value.version), messageId: requireUuid(value.messageId, 'Control message ID'), type, sessionId: requireUuid(value.sessionId, 'Control session ID'), senderDeviceId: requireUuid(value.senderDeviceId, 'Control sender device ID'), sequence: requireSequence(value.sequence), timestamp: requireTimestamp(value.timestamp), payload: parsePayload(type, value.payload) } as AnyControlMessage; }
export function encodeHandshakeFrame(frame: ControlHandshakeFrame): string { return JSON.stringify(frame); }
export function decodeHandshakeFrame(raw: string): ControlHandshakeFrame {
  const value = parseJson(raw);
  if (value.kind === 'hello1') { if (!exactKeys(value, ['kind', 'version', 'helloId', 'sessionId', 'senderDeviceId', 'nonce', 'timestamp', 'mac'])) throw new ControlCodecError('hello1 has unsupported fields.'); return { kind: 'hello1', version: requireVersion(value.version), helloId: requireUuid(value.helloId, 'Control hello ID'), sessionId: requireUuid(value.sessionId, 'Control session ID'), senderDeviceId: requireUuid(value.senderDeviceId, 'Control sender device ID'), nonce: requireNonce(value.nonce), timestamp: requireTimestamp(value.timestamp), mac: requireMac(value.mac) } satisfies Hello1Frame; }
  if (value.kind === 'hello2') { if (!exactKeys(value, ['kind', 'version', 'helloId', 'sessionId', 'senderDeviceId', 'nonce', 'echoNonce', 'initiatorDeviceId', 'timestamp', 'mac'])) throw new ControlCodecError('hello2 has unsupported fields.'); return { kind: 'hello2', version: requireVersion(value.version), helloId: requireUuid(value.helloId, 'Control hello ID'), sessionId: requireUuid(value.sessionId, 'Control session ID'), senderDeviceId: requireUuid(value.senderDeviceId, 'Control sender device ID'), nonce: requireNonce(value.nonce), echoNonce: requireNonce(value.echoNonce), initiatorDeviceId: requireUuid(value.initiatorDeviceId, 'Control initiator device ID'), timestamp: requireTimestamp(value.timestamp), mac: requireMac(value.mac) } satisfies Hello2Frame; }
  throw new ControlCodecError('Control handshake kind is invalid.');
}
export function encodeSealedControlFrame(frame: SealedControlFrame): string { return JSON.stringify(frame); }
export function decodeSealedControlFrame(raw: string): SealedControlFrame { const value = parseJson(raw); if (!exactKeys(value, ['kind', 'version', 'sessionId', 'senderDeviceId', 'sequence', 'type', 'sealed'])) throw new ControlCodecError('Sealed control frame has unsupported fields.'); if (value.kind !== 'sealed') throw new ControlCodecError('Sealed control frame kind is invalid.'); if (!isControlMessageType(value.type)) throw new ControlCodecError('Sealed control type is invalid.'); if (typeof value.sealed !== 'string' || !value.sealed.startsWith('c1:') || value.sealed.length > MAX_SEALED_WIRE_CHARS) throw new ControlCodecError('Sealed control payload is invalid.'); return { kind: 'sealed', version: requireVersion(value.version), sessionId: requireUuid(value.sessionId, 'Control session ID'), senderDeviceId: requireUuid(value.senderDeviceId, 'Control sender device ID'), sequence: requireSequence(value.sequence), type: value.type, sealed: value.sealed }; }
