plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.partnerscreen.requestnotification'
version = '0.1.0'

android {
  namespace "com.partnerscreen.requestnotification"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  testOptions {
    unitTests.includeAndroidResources = true
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'org.robolectric:robolectric:4.16.1'
  testImplementation 'androidx.test:core:1.7.0'
}
